export const TEMPLATE_PAGINATION_LIMIT = 12;
export const CONTENT_HISTORY_PAGINATION_LIMIT = 10;
export const PAYMENT_HISTORY_TABLE_PAGINATION_LIMIT = 10;
export const MAX_CONTENT_LENGTH = 5000;
export const MAX_ICON_FILE_SIZE = 1024 * 1024 * 1;